import java.awt.Component;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author Seth Yost
 */
public class Buddy_gui extends javax.swing.JFrame {

    /**
     * Creates new form Buddy_gui
     */
    public Buddy_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        All_contacts = new JList();
        jLabel1 = new JLabel();
        jScrollPane2 = new JScrollPane();
        Buddies = new JList();
        jLabel2 = new JLabel();
        Chat = new JButton();
        AddToBuddies = new JButton();
        GroupChat = new JButton();
        RemoveBuddy = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        All_contacts.setModel(new DefaultListModel() {
        	//TODO:get all online users
            
      		//add all users to list      		
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(All_contacts);

        jLabel1.setText("All Contacts:");

        Buddies.setModel(new DefaultListModel() {
        	//TODO:get online buddies
      		
      		//add buddies to buddy list        	
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(Buddies);

        jLabel2.setText("Buddies:");

        Chat.setText("Chat");
        Chat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChatMouseClicked(evt);
            }
        });

        AddToBuddies.setText("Add to Buddies");
        AddToBuddies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddToBuddiesMouseClicked(evt);
            }
        });
        AddToBuddies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBuddiesActionPerformed(evt);
            }
        });
        
        RemoveBuddy.setText("Remove Buddy");
        RemoveBuddy.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveBuddyMouseClicked(evt);
        	}
        });

        GroupChat.setText("Group Chat");
        GroupChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GroupChatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(AddToBuddies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    	.addComponent(RemoveBuddy)
                        .addComponent(GroupChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Chat)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddToBuddies)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                	.addComponent(RemoveBuddy)
                    .addComponent(Chat)
                    .addComponent(GroupChat))
                .addContainerGap())
        );
        
        /*
    	 * Codes are:
    	 * 0  - CREATE ACCOUNT		C->S
    	 * 1  - LOGON				C->S
    	 * 2  - LOGOFF				C->S
    	 * 3  - MESSAGE				C<->S
    	 * 4  - BUDDY ON			S->C
    	 * 5  - BUDDY OFF			S->C
    	 * 6  - SUCCESSFUL LOGON	S->C
    	 * 7  - FAILED LOGON		S->C
    	 * 8  - ADD BUDDY			C->S
    	 * 9  - REMOVE BUDDY		C->S
    	 * 10 - TYPING				C<->S
    	 * 11 - ENTERED TEXT		C<->S
    	 * 12 - MESSAGE FAILED		S->C
    	 * 13 - SET PROFILE			C->S
    	 * 14 - GET PROFILE 		S->C
    	 */

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings({ "rawtypes", "unchecked" })
	protected void RemoveBuddyMouseClicked(MouseEvent evt) {//GEN-FIRST:event_ChatMouseClicked
		// TODO Auto-generated method stub
    	DefaultListModel listModel = new DefaultListModel();
    	DefaultListModel old = (DefaultListModel) Buddies.getModel();
    	for (int i = 0; i < old.size(); i++)
    	{
    		if(old.equals(Buddies.getSelectedValue()))
    		{
    			listModel.removeElement(old.getElementAt(i));
    		}
    	}
		
	}//GEN-LAST:event_ChatMouseClicked

	private void ChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChatMouseClicked
        
    	List user = Buddies.getSelectedValuesList();
    	String users = user.toString();
    	Chat_gui chat = new Chat_gui(users.substring(1, users.length()-2));
    	chat.setTitle("Chat");
    	chat.setVisible(true);
    	
    }//GEN-LAST:event_ChatMouseClicked

    private void AddToBuddiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBuddiesActionPerformed
        // TODO add your handling code here:
    	
    	
    }//GEN-LAST:event_AddToBuddiesActionPerformed

    @SuppressWarnings({ "rawtypes", "unchecked" })
	private void AddToBuddiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddToBuddiesMouseClicked
    	
    	DefaultListModel listModel = new DefaultListModel();
    	DefaultListModel old = (DefaultListModel) Buddies.getModel();
    	for (int i = 0; i < old.size(); i++)
    	{
    		listModel.addElement(old.getElementAt(i));
    	}
    	listModel.addElement(Buddies.getSelectedValue());
    	//TODO: add to database buddy list
    	
    }//GEN-LAST:event_AddToBuddiesMouseClicked

    @SuppressWarnings("rawtypes")
	private void GroupChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GroupChatMouseClicked
        // TODO add your handling code here:
    	List user = Buddies.getSelectedValuesList();
    	String users = user.toString();
    	Chat_gui chat = new Chat_gui(users.substring(1, users.length()-2));
    	chat.setVisible(true);
    }//GEN-LAST:event_GroupChatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buddy_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buddy_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buddy_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buddy_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buddy_gui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToBuddies;
    private javax.swing.JList All_contacts;
    private javax.swing.JList Buddies;
    private javax.swing.JButton Chat;
    private javax.swing.JButton GroupChat;
    private javax.swing.JButton RemoveBuddy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
