import java.io.PrintWriter;
import java.util.Calendar;

import javax.swing.text.BadLocationException;
import javax.swing.text.StyledDocument;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Seth Yost
 */
public class Chat_gui extends javax.swing.JFrame {

    /**
     * Creates new form Chat_gui
     * @param buddy_gui 
     */
	private Buddy_gui buddy = null;
	private PrintWriter write = null;
    public Chat_gui(String user, Buddy_gui buddy_gui) {
        initComponents();
        buddy = buddy_gui;
        write = buddy_gui.getWriter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        Message = new javax.swing.JTextArea();
        Send = new javax.swing.JButton();
        Enter_send = new javax.swing.JCheckBox();
        //chat_with_label = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        conversationPane = new javax.swing.JTextPane();
        doc = conversationPane.getStyledDocument();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Message.setColumns(20);
        Message.setRows(5);
        Message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MessageKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(Message);

        Send.setText("Send");
        Send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendMouseClicked(evt);
            }
        });

        Enter_send.setText("send on Enter");
        Enter_send.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Enter_sendStateChanged(evt);
            }
        });
        Enter_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enter_sendActionPerformed(evt);
            }
        });

        //chat_with_label.setText("jLabel1");

        conversationPane.setEditable(false);
        jScrollPane4.setViewportView(conversationPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 232, Short.MAX_VALUE)
                        .addComponent(Enter_send)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Send))
                    .addGroup(layout.createSequentialGroup()
                        //.addComponent(chat_with_label)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
               // .addComponent(chat_with_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Send)
                    .addComponent(Enter_send)))
        );

        pack();
    }

    private void Enter_sendActionPerformed(java.awt.event.ActionEvent evt) {
        
    	
    }

    private void Enter_sendStateChanged(javax.swing.event.ChangeEvent evt) {
        
    	
    }

    private void SendMouseClicked(java.awt.event.MouseEvent evt) {
    	String mess = Message.getText();
    	if(!mess.equalsIgnoreCase("\n"))
    	{
	    	Calendar cal = Calendar.getInstance();
			String scal = cal.getTime().toLocaleString();
	    	mess = buddy.getTitle() + "@ " + scal + ": " + mess + "\n";
	    	try
	    	{
	    		doc.insertString(doc.getLength(), mess, null);
	    	}
	    	catch(BadLocationException e)
	    	{
	    		System.out.println(e.getStackTrace());
	    	}
	    	Message.setText("");
	    	String mes = "3 " + buddy.getTitle() + " " + getTitle() + " " + Message.getText();
	    	write.print(mes);
	    	write.flush();
    	}
    }

    private void MessageKeyTyped(java.awt.event.KeyEvent evt) {
    	//if checked send on enter otherwise do nothing.
    	if(Enter_send.isSelected())
    	{
    		char temp = evt.getKeyChar();
    		if(temp == '\n')
    		{
    			String mess = Message.getText();
    			if(!mess.equalsIgnoreCase("\n"))
    	    	{
	    	    	Calendar cal = Calendar.getInstance();
					String scal = cal.getTime().toLocaleString();
	    	    	mess = buddy.getTitle() + "@ " + scal + ": " + mess;
	    	    	try
	    	    	{
	    	    		doc.insertString(doc.getLength(), mess, null);
	    	    	}
	    	    	catch(BadLocationException e)
	    	    	{
	    	    		System.out.println(e.getStackTrace());
	    	    	}
	    	    	Message.setText("");
	    	    	String mes = "3 " + buddy.getTitle() + " " + getTitle() + " " + Message.getText();
	    	    	write.print(mes);
	    	    	write.flush();
    	    	}
    		}    		
    	}
    	
    }
    
    //gets the message and appends it to the window
    protected void message(String From, String mess)
    {
    	Calendar cal = Calendar.getInstance();
		String scal = cal.getTime().toLocaleString();
    	mess = From + "@ " + scal + ": " + mess;
    	try
    	{
    		doc.insertString(doc.getLength(), mess, null);
    	}
    	catch(BadLocationException e)
    	{
    		System.out.println(e.getStackTrace());
    	}
    }
    
    // Variables declaration - do not modify
    private javax.swing.JCheckBox Enter_send;
    private javax.swing.JTextArea Message;
    private javax.swing.JButton Send;
    //private javax.swing.JLabel chat_with_label;
    private javax.swing.JTextPane conversationPane;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTree jTree1;
    private StyledDocument doc;
    // End of variables declaration
}
